name: Deploy

on:
  push:
    branches: [main]

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build & Deploy
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          HOST_NAME: ${{ secrets.HOST_NAME }}
          USER_NAME: ${{ secrets.USER_NAME }}

        run: |
          # Guardamos la llave privada y le asignamos los permisos correctos
          echo "$PRIVATE_KEY" > redes.pem && chmod 400 redes.pem

          # Nos conectamos a la instancia EC2 usando SSH
          ssh -o StrictHostKeyChecking=no -i redes.pem ${USER_NAME}@${HOST_NAME} '

          # Verificamos si el directorio es un repositorio Git
          if [ ! -d "/home/ubuntu/Sandy/.git" ]; then
            # Si no es un repositorio Git, clonamos el repositorio
            git clone https://github.com/Sandyslein/database.git /home/ubuntu/Sandy;
          fi

          # Comandos para desplegar el contenedor de Docker
          cd /home/ubuntu/Sandy &&

          # Actualizamos el repositorio
          git checkout main &&
          git fetch --all &&
          git reset --hard origin/main &&
          git pull origin main &&

          # Construimos y ejecutamos el contenedor de Docker
          sudo docker compose down &&
          sudo docker compose build &&
          sudo docker compose up -d
          '
